-- 格式
-- -------------------------------------------------
-- CREATE TRIGGER 
--     [trigger_name] 
-- [trigger_time] [trigger_event] ON
--     [table_name] 
-- FOR EACH ROW 
--     [trigger_body]
-- -------------------------------------------------
